### ISSUE TITLE
Trim email address on login screen

### ISSUE THREAD

**Issue by enmosys** [codeforbtv/green-up-app-old#190] opened 2019-11-07 13:01 UTC
On my Android phone, when logging in, Android suggests previously-used email addresses for login. If one of these is chosen, the email address that Android enters in the edit box is suffixed by a space, which causes login to fail.

This seems like it could trip up less technical Android users. Trimming the email address on form submission should fix it.

**Comment by kmeyersvt** [comment] 2020-04-07 22:38
closing duplicate of 291

**Closed as completed by kmeyersvt** 2020-04-07 22:38 UTC
Labels: good first issue, Priority: Medium
