### ISSUE TITLE
Clicking on 'manage your team' restarts the app

### ISSUE THREAD

**Issue by anismemon** [codeforbtv/green-up-app-old#293] opened 2020-03-28 19:37 UTC
**Describe the bug**

I created a team, which now shows up on the Homepage, but if I click on it, it simply takes me back to the app's logo screen which, after a few seconds, returns to the homepage.

**To Reproduce**
1. Go to 'Homepage'
2. Click on 'Manage Your Team'

**Expected behavior**

Go into my team info

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J7
 - OS: 8.1.0
 - Browser: Samsung Internet
 - Version: not sure

**Comment by kristylynn1984** [comment] 2020-03-31 23:14
I'm experiencing the same issue but every few attempts the app crashes altogether (screenshot attached). 

Device: Samsung Galaxy S7
OS: Android 8.0.0 / Samsung Experience 9.0

![Screenshot_20200331-191041_Expo](https://user-images.githubusercontent.com/62626323/78083521-b7d01980-7383-11ea-9156-9045b365308e.jpg)

**Comment by nfloersch** [comment] 2020-04-17 05:06
Duplicate of #274

**Closed as completed by nfloersch** 2020-04-17 05:06 UTC
Labels: Type: Bug, MUSTFIX
