### ISSUE TITLE
Clicking "Trash Disposal" crashes app

### ISSUE THREAD

**Issue by doub1ejack** [codeforbtv/green-up-app-old#310] opened 2020-04-04 15:19 UTC
**Describe the bug**
From the home screen, when I click the "Trash Disposal" tile the app crashes.

**Screenshots**
<img src="https://user-images.githubusercontent.com/1809882/78454413-e260f180-7665-11ea-9257-2ff529ae9352.png" width=400/>

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - Green Up App Version: 3.0.6

**Comment by nfloersch** [comment] 2020-04-05 02:52
Duplicate of issue #305 - refer to issue 305 for additional background.

**Comment by nfloersch** [comment] 2020-04-12 06:52
Just a note - the error is at least partly on line 156 of the Trash Disposal Screen index.js file, in the code:

```
const teamOptions = Object.entries(currentUser.teams || {}).map((entry: [string, Object]) => ({
        id: entry[0],
        name: state.teams.teams[entry[0]].name
    }));
```
It seems that there is perhaps bad data that is hitting the array mapping process... it complains about an empty value and the .name not being defined. A try-catch block is working for me but I haven't committed it yet, still trying to sort out more of the why on this issue.

**Comment by nfloersch** [comment] 2020-04-13 05:38
Update - I have code that eliminates this issue in a literal sense. However, the heart of the issue is something to do with the user's initial location and the initialization of the mini map on the trash drop form... and i haven't got that worked out. Right now it doesn't crash anymore, but an Android user cannot drop trash anywhere other than off the cost of Africa.

**Comment by kmeyersvt** [comment] 2020-05-18 15:01
This passes in 5.0.26

**Closed as completed** 2022-07-12 21:34 UTC
Labels: Priority: High, MUSTFIX, PassedQA
