### ISSUE TITLE
Tapping "Trash Disposal" on iPhone crashes the app

### ISSUE THREAD

**Issue by iritush** [codeforbtv/green-up-app-old#329] opened 2020-04-15 01:01 UTC
**Describe the bug**
Tapping "Trash Disposal" on iPhone crashes the app

**To Reproduce**
Tap "Trash Disposal"

**Expected behavior**
Trash disposal launches

**Screenshots**

**App Version (found on "Menu" screen):** [e.g. "v3.0.6"]
3.0.13, 2020-4-13
Firebase Target greenupvermont-qa
**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 13.3.1

**Phone Emulators**
 - OS: [e.g. iOS or Android]
 - Version [e.g. iPhone 6, iPad, Google Pixel]

**Additional context**
Crash log attached
[OrgGreenupvermontApp-2020-04-14-204727.ips.beta.txt](https://github.com/codeforbtv/green-up-app/files/4478522/OrgGreenupvermontApp-2020-04-14-204727.ips.beta.txt)

**Comment by iritush** [comment] 2020-04-15 01:02
Related? https://github.com/codeforbtv/green-up-app/issues/310

**Comment by nfloersch** [comment] 2020-04-17 05:01
Duplicate of #310

**Closed as completed by nfloersch** 2020-04-17 05:01 UTC
